Step2 / Header Categories list / Ajax / Main Slider Features.
code-squad/javascript-freestyle-level3 pull request #4
Opened 2018-06-05 15:06 UTC by likedemian

**Header 카테고리 항목**
- 카테고리에 마우스를 올리면 레이어가 노출됩니다. 
- 카테고리 내 하위 항목에 마우스를 올리면 밑줄이 생기고, 클릭하면 하위 항목 특성에 따른 하위 텍스트가 나타납니다.
- 하위 텍스트에 마우스를 올리면 해당 텍스트의 투명도가 감소합니다.
- 마우스가 지정한 영역을 벗어나면 노출된 레이어는 사라집니다.

**Ajax**
- nextstep에 올라온 강의를 참고해서 Ajax 호출하는 메서드를 제작했습니다.

**Main Slider**
- 좌우 버튼을 누르면 투명도가 감소하면서 화면이 전환됩니다. 추후 기능 보강하겠습니다.

2018-06-07 02:42 UTC, crongro requested changes
캡처링/버블링 공부하기. 

데이터 갱신과 Ajax요청타이밍을 어떻게 효율적으로 구현할 수 있을지 고민해보기.

css 이름 줄여보기.

함수형으로 계속 구현해보세요. 무언가 필요하면 나중에 리팩토링.

step 중간에 test code를 구현해보세요.

2018-06-07 02:42 UTC, nigayo commented on src/js/app.js
> +    return filterLists.innerHTML += showItems(categoriesLists[0], 'header__gnb__left-nav__categories-list__filter-list__template');
function html (target, htmlData){} 
이와 같은 함수로 중복을 제거가능.

2018-06-07 02:42 UTC, nigayo commented on src/js/data.js
> +const mainCategories = [
실제서버에서 데이터를 가져오는 것과 유사하게 동작되면 좋겠어요.
따라서 data.js의 데이터 구조를 json포맷으로 변경합니다.
data/mainCategories.json 
data/categoriesLists.json 
각각 파일은 json포맷에 맞게 구성돼어 있어야 함.

저 두 개의 json 파일은 Ajax요청을 해서 가져와야 함.

2018-06-07 02:42 UTC, nigayo commented on src/js/app.js
> +getMovieData();
시작과 동시에 처리되는 함수들은 모아두는 게 좋고요. 
dom loaded이벤트이후에 처리되도록 하세요.

2018-06-07 02:42 UTC, nigayo commented on src/js/app.js
> +    elem.addEventListener('click', e => {
이벤트 델리게이션을 활용하면 좋겠네요.

2018-06-12 05:17 UTC, crongro requested changes
리뷰합니다.

2018-06-12 05:17 UTC, nigayo commented on index.html
> +        <li class="left-nav__categories">
축 클래스이름 줌.

2018-06-12 05:17 UTC, nigayo commented on src/js/app.js
> +const $on = (selector, type, callback) => {
왜 $로 시작해요? 궁금하네요. 이녀석만 $로 시작해서요.

2018-06-12 05:17 UTC, nigayo commented on src/js/app.js
> +const $on = (selector, type, callback) => {
하나의 소스코드 파일이  어느정도는 하나의 모듈로써 특정 역할을 가진 녀석들로만 구성되는 게  좋아요.

app.js 가 어떤 역할을 할텐데요. $on 와 같은 성격의 함수들은 여기에 있는게 좋을까요?

2018-06-12 05:17 UTC, nigayo commented on src/js/app.js
> +const init = () => {
init보다는 좀더 구체적인 이름을 쓸 수 있을거 같아요.

2018-06-12 05:17 UTC, nigayo commented on src/js/app.js
> +const categoriesTemplate = (function () {
동사+명사로.

2018-06-12 05:17 UTC, nigayo commented on src/js/app.js
> +    let jsonData = JSON.parse(this.responseText);
여기서도 destructuring 을 쓸 수 있어보여요.

2018-06-12 05:17 UTC, nigayo commented on src/js/app.js
> +    return renderTemplate(filters, data, 'left-nav__categories-list__template') && renderTemplate(filterLists, data[0].detail, 'left-nav__categories-list__filter-list__template');
renderTemplate 의 반환값이 어떻게 되죠? 
반환값에 따라서 다르게 체크하는 거 같은데요. 어떤 반환값을 예상한 것인지 모호합니다.

2018-06-12 05:17 UTC, nigayo commented on src/js/app.js
> +      data.forEach((el, i) => {
filter 이후에 forEach 를 쓰면  조건문이 없어지지 않을까요?

2018-06-12 05:17 UTC, nigayo commented on src/js/app.js
> +    e.target === categoriesBox || categoriesNav && categoriesBox.classList.remove('active')
이런 연산자 사용은 좀 가독성이 떨어져요. 
xxx || xxx && xxx

2018-06-12 05:17 UTC, nigayo commented on src/js/app.js
> +  const getFilter = (data) => {
내부함수로 두지말고 외부함수로 분리해서 호출해도 될 거 같아요.
이 부분에서 내부 함수의  큰 장점을 느끼진 못하겠어요. 어떤 특별한 이유가 있나요?

2018-06-15 03:19 UTC, leee-dw commented on src/js/app.js
> +const $on = (selector, type, callback) => {
helper.js 파일을 제작해서 따로 모아두겠습니다.

2018-06-15 03:19 UTC, leee-dw commented on src/js/app.js
> +const init = () => {
네 다른 메서드 네임을 생각해보겠습니다.

2018-06-15 03:19 UTC, leee-dw commented on src/js/app.js
> +const categoriesTemplate = (function () {
넵

2018-06-15 03:19 UTC, likedemian commented on src/js/app.js
> +    return renderTemplate(filters, data, 'left-nav__categories-list__template') && renderTemplate(filterLists, data[0].detail, 'left-nav__categories-list__filter-list__template');
첫 번째는 카테고리에서 대분류를 나타내는 renderTemplate 메서드고, 
두 번째는 대분류 내 하위 목록을 나타내는 renderTemplate메서드입니다.

2018-06-15 03:19 UTC, likedemian commented on src/js/app.js
> +  const getFilter = (data) => {
Module Prototype을 사용해서 내부함수 은닉을 시도했는데, 잘 안되었고, 분리하지 않은 채로 나뒀습니다. 내부함수로 둔 특별한 이유는 없습니다. 분리하도록 하겠습니다.

2018-06-15 03:19 UTC, likedemian commented on src/js/app.js
> +    e.target === categoriesBox || categoriesNav && categoriesBox.classList.remove('active')
네 수정하겠습니다.

2018-06-15 06:09 UTC, crongro requested changes
다소 수정이 필요함~

2018-06-15 06:09 UTC, crongro commented on src/js/data.json
> +{
json 표준 포맷을 잘 썼네요.
online으로 유효성 검증하는 것도 있으니 참고하세요.

2018-06-15 06:09 UTC, crongro commented on src/js/app.js
> +  })();
즉시실행함수를 써야하는 이유는  뭐에요?

2018-06-15 06:09 UTC, crongro commented on src/js/app.js
> +import { $on, $qs, $qsa } from './helper.js';
app.js 를  진입점이 되는 거고, 
서비스의 모듈들을 만들고 그걸 불러오도록 해보세요.

2018-06-15 06:09 UTC, crongro commented on src/js/app.js
> +const switchFilter = (data) => {
함수이름에 코드의 동작을 설명하지말고, 함수의 의미(맥락)를 넣는게 더 좋아요.

2018-06-15 06:09 UTC, crongro commented on src/js/app.js
> +const catModule = (() => {
Cat??

2018-06-15 06:09 UTC, crongro commented on src/js/temp.js
> +          return makeFilter(filterLists, data[idx].detail, 'header__gnb__left-nav__categories-list__filter-list__template')
아무리 생각해도 이름이 너무  길어요..
header__gnb__left-nav__categories-list__filter-list__template

2018-06-15 06:09 UTC, crongro commented on src/js/temp.js
> +      mainSlides[count + 2].style.opacity = '1';
숫자 1,2 는 뭘 뜻하나요?

2018-06-15 06:09 UTC, crongro commented on src/js/temp.js
> +    return makeFilter(filters, data, 'header__gnb__left-nav__categories-list__template') && makeFilter(filterLists, data[0].detail, 'header__gnb__left-nav__categories-list__filter-list__template');
가로스크롤이 생길지경이니 이름을 좀 줄이는 게 답일 듯.

2018-06-15 06:09 UTC, crongro commented on src/js/temp.js
> +categoriesLink.addEventListener('pointerover', e => {
똑같은 세  개의 이벤트핸들러가 있는데, 이벤트 델리게이션을 쓸 수는 없을까요?

2018-06-15 06:09 UTC, crongro commented on src/js/temp.js
> +const template = (templateid, data) => {
temp는 무슨파일인지... 파일이름에서 해당 소스코드의 역할을 알 수 있게 하세요.

2018-06-25 05:51 UTC, crongro requested changes
모듈 분리가 전에보다 잘 됐네요.
리뷰남겨요.

2018-06-25 05:51 UTC, nigayo commented on src/js/async.js
> +export const loadData = (url, handler) => {
async 파일을 별도 분리했네요.
이렇게 파일 수준으로 분리하는 기준은 어떤 건가요?

2018-06-25 05:51 UTC, nigayo commented on src/js/helper.js
> +export const $on = (target, type, callback) => {
helper 에 어울리는 것들이 있으면 계속 추가하세요.

2018-06-25 05:51 UTC, nigayo commented on src/js/helper.js
> +export function $qsa(selector, scope = document) {
이건 큰 문제는 아닙니다. 
제  생각에는 파라미터의 순서가 바뀌면  더 사고의 흐름과 일치할 거 같네요.
qs도 그렇고 qsa도 그렇고요.

2018-06-25 05:51 UTC, nigayo commented on src/js/view/CategoriesView.js
> +    return $on(selector, 'mouseover', event => event.target === link && box.classList.add('active'));
$on이 무엇을 반환하길래?  expandCategories 함수는 반환값이 있나요?

2018-06-25 05:51 UTC, nigayo commented on src/js/view/CategoriesView.js
> +    return $on(selector, 'mouseleave', event => { if (event.target === box || selector) box.classList.remove('active'); })
여기부분도 반환값이 있는 것이 어색..

2018-06-25 05:51 UTC, nigayo commented on src/js/view/CategoriesView.js
> +      this.filterLists.insertAdjacentHTML('beforeend', renderCategoryListsTemplate(category.filter(filterByCategories)[0].detail))
한줄로 쭉 쓰면 보기도 어렵고 디버깅도 어려워요.(중간에 어떤 값을 알고 싶을때 빨리 알기가 어렵죠)
renderCategoryListsTemplate () 결과를  먼저 받고 insertAdjacentHTML메서드에서 사용하면 더 보기 좋을 듯.

2018-06-25 05:51 UTC, nigayo commented on src/js/view/CategoriesView.js
> +export class CategoriesController {
하나의 파일에 하나의 클래스가 어울릴 듯. 
하나의 클래스라는 것이 하나의 단위모듈로 보니까요.

2018-06-25 05:51 UTC, nigayo commented on src/sass/header/_categories.sass
> +.left-nav__categories-list__filtered__item
점점 줄지만 , 상대적으로 일반서비스에 비하면 길어요.

2018-06-25 05:51 UTC, nigayo commented on src/sass/main/content/_main-content.sass
> +  border: 0.1vw solid #181818
vw 의 브라우저 지원범위가 어떤지 그냥 한번 들여다보세요.

2018-06-25 07:12 UTC, likedemian commented on src/js/async.js
> +export const loadData = (url, handler) => {
model, view, controller 중에 어느 곳에  넣어야할지 몰라서 일단은 별도 파일로 분리했습니다. 차후 재배치 하겠습니다.

2018-06-25 07:12 UTC, likedemian commented on src/js/helper.js
> +export const $on = (target, type, callback) => {
넵!!

2018-06-25 07:26 UTC, leee-dw commented on src/js/view/CategoriesView.js
> +    return $on(selector, 'mouseover', event => event.target === link && box.classList.add('active'));
그냥 클래스를 추가하는 메서드입니다 반환값은 없습니당...

2018-06-25 07:30 UTC, likedemian commented on src/js/view/CategoriesView.js
> +      this.filterLists.insertAdjacentHTML('beforeend', renderCategoryListsTemplate(category.filter(filterByCategories)[0].detail))
renderCategoryListsTemplate() 결과값을 받고, inserAdjacentHTML 메서드에 내용을 추가하겠습니다.

2018-06-25 07:30 UTC, likedemian commented on src/js/view/CategoriesView.js
> +export class CategoriesController {
네 컨트롤러 클래스는 다른 파일로 분리하겠습니다.

2018-06-26 01:05 UTC, nigayo commented on src/js/view/CategoriesView.js
> +    return $on(selector, 'mouseover', event => event.target === link && box.classList.add('active'));
그럼 return 이 필요 없겠군요

2018-09-16 11:58 UTC, merged